# @Issue(
#   "Create an 'f_sails_bg' image"
#   type="task"
#   priority="normal"
# )
FROM krystalcode/f_sails

ENV NODE_VERSION 5.0.0

# Globally install additional node tools by the project.
RUN . $HOME/.nvm/nvm.sh && \
    nvm use ${NODE_VERSION} && \
    npm install -g bower gulp

# Run the application.
CMD . ${HOME}/.nvm/nvm.sh && \
    nvm use ${NODE_VERSION} && \
    sails lift
